// import { DollarSign, TrendingUp, Handshake, Coins } from "lucide-react";

export default function Component() {
  const values = [
    {
      title: "Interest",
      description: "Interest from secured agricultural loans",
      image: "/interest.svg",
    },
    {
      title: "Profit",
      description: "A Share of Company Profits",
      image: "/profit.svg",
    },
    {
      title: "Interest",
      description: "Profits generated by successful farming projects",
      image: "/interest2.svg",
    },
    {
      title: "Staking",
      description: "A stake in the long term growth of the platform",
      image: "/staking.svg",
    },
  ];

  return (
    <div className="bg-transparent pb-4 2xl:py-16 md:py-8 px-4">
      <div className="max-w-7xl 2xl:max-w-[86%] mx-auto">
        <h1 className="text-xl lg:text-3xl 2xl:text-5xl font-bold text-center mb-2 md:mb-8 2xl:mb-16 text-[#7fe4ff]">
          Our Values
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {values.map((value, index) => {
            return (
              <div className="relative p-3 ">
                <div className="absolute top-0 right-0 bg-[#FBC100] rounded-md z-20">
                  {/* <IconComponent className="w-8 h-8 text-white" /> */}
                  <img src={value.image} alt="image" height={32} width={32} />
                </div>
              <div
                key={index}
                className="bg-transparent/70 border border-[#7fe4ff] rounded-2xl p-2 lg:p-4 2xl:p-8 h-full 2xl:min-h-[200px] flex flex-col justify-between"
              >
                

                <div className="mt-1 2xl:mt-8">
                  <h2 className="text-xl lg:text-2xl 2xl:text-3xl font-bold text-[#7FE4FF] mb-1 2xl:mb-4">
                    {value.title}
                  </h2>
                  <p className="text-white  text-sm lg:text-sm 2xl:text-lg leading-relaxed">
                    {value.description}
                  </p>
                </div>
              </div>
                </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
